Handle missing log handler when reloading (#1573)
It seems that in some situations, the SDK may cause an exception when
hot reloading because the `customLogHandler` is undefined.
```
console.js:661 TypeError: customLogHandler is not a function (it is undefined)
    at anonymous (purchases.js:74:21)
    at apply (native)
    at emit (EventEmitter.js:130:36)
    at apply (native)
    at anonymous (RCTDeviceEventEmitter.js:14:59)
    at emit (RCTDeviceEventEmitter.js:33:5)
```

This doesn't seem to be easy to repro but basically, in some scenarios,
it seems we might keep the native log handler reference, but the RN side
would be lost. In this case, it would cause those errors. This should
fix those, by ignoring the logs, at least until a new listener is set on
the RN side.